model_list:
  - model_name: general
    litellm_params:
      model: openai/general
      api_base: http://internal-model-router:8101/v1
      api_key: sk-internal

  - model_name: autocomplete
    litellm_params:
      model: openai/autocomplete
      api_base: http://internal-model-router:8102/v1
      api_key: sk-internal

  - model_name: quick-chat
    litellm_params:
      model: openai/quick-chat
      api_base: http://internal-model-router:8103/v1
      api_key: sk-internal

  - model_name: vision
    litellm_params:
      model: openai/vision
      api_base: http://internal-model-router:8104/v1
      api_key: sk-internal

litellm_settings:
  drop_params: true
